### ISSUE TITLE
Llistat de tasques

### ISSUE THREAD

**Issue by dleiva29** [dleiva29/UOC_Tipologia_Euroleague#1]
- [x] Extreure **Jugadors** i links de cada equip

- [x] Extreure **Estadístiques**  de cada jugador

- [x] Crear **arxiu** .csv

**Comment by dleiva29** [comment]
Crec que podem extreure el jugadors directament sense extreure primer els equips. Si anem a la pàgina de jugadors i els extreïem alfabéticament.

**Comment by AlvaroDiazS** [comment]
Crec que la manera d'extreure les estadístiques és molt variada i podem trobar més d'1 camí per arribar-hi. La clau es definir exactament que volem i extreure-ho i mirar quina és la millor manera d'arribar-hi. 
Si l'extracció es per la pàgina de jugadors, llavors només tindrem les estadístiques actuals i històriques dels jugadors que participin aquest any. No construirem un repositori de dades històriques de tots els jugadors que han jugat a la Eurolliga.

Com no sé exactament com funciona el BeautifulSoup i com extreu les coses, podem començar de manera senzilla d'una manera i en tot cas acabar de definir el projecte més endavant segons les dades que siguem  capaços d'extreure. Jo per la meva part ja estic disponible.

Álvaro

**Comment by dleiva29** [comment]
- Si vols podem començar amb les estadístiques mitjanes de cada jugador. Dintre de "Career stats" hi ha la fila de "Averages". Podem començar per aquesta. Podem afegir la info de la capçalera de cada jugador, per exemple "REAL MADRID 6 FORWARD
HEIGHT: 2.02 BORN: 15 DECEMBER, 1995 NATIONALITY: SPAIN" i les de l'average "

G | Pts | Avg | 2FG | % | 3FG | % | FT | % | Reb | St | As | Bl
52 | 401 | 7.7 | 96/194 | 49.5 | 50/118 | 42.4 | 59/76 | 77.6 | 3 | 0.4 | 1.7 | 0

- No se com d'extens vols fer la PAC, però podem començar amb això i si el veiem just, doncs ampliem, vale?

- He creat una branca "init" per anar fent. Hi ha un arxiu prueba.py al que vaig fent proves. Per ara he aconseguit extreure els links a les webs de cada jugador i el seu nom. A veure que et sembla.

**Comment by AlvaroDiazS** [comment]
Bon dia,

Avui intentaré dedicar-me durant els ratets lliures que tingui el dia a mirar documentació i a fer més proves. També repasarè el codi que vas fer ahir, encara que tenia bona pinta. Faig un altre fitxer de proves o vaig retocant el mateix.

Respecte a les estadístiques, podem treure els totals com dius o potser podem treure totes les temporades per a tenir una mica més d'info. De totes maneres, miro a veure que aconseguixo.

Una pregunta per a dummys. Cada dia que obro el Github Desktop, s'actualitzen de manera automàtica els fitxers que hi ha en local o he de prèmer un botó per a fer-ho? He buscat per internet i no em queda clar del tot. Potser és el botó Fetch Origin? O he de fer de Repository ->> Pull?
