### ISSUE TITLE
Stats per temporada

### ISSUE THREAD

**Issue by AlvaroDiazS** [dleiva29/UOC_Tipologia_Euroleague#2]
Afegit un csv extra amb nom jugadors_temporada amb les dades de cada temporada. 

Tasques a corregir: 
- [x] Corregir nom_Complet. Treure []
- [x] Extracció per a tot abecedari, no només A
- [x] Homogeneitzar noms variables
- [x] Netejar codi en general

**Comment by AlvaroDiazS** [comment]
He tocado el boleano que indica si hay datos de Euroliga lo he modificado ya que el cambio que tenías en els script Pruebas.py no me funcionaba correctamente. En PruebasAlvaro.py puedes ver la otra manera, muy similar.

Además estoy generando todo el dataset.

**Comment by dleiva29** [comment]
Tiene muy buena pinta!. Esto casi lo tenemos. 

Con respecto a:
>
> * [ ]  Corregir nom_Complet. Treure []

Creo que añadiendole un [0] al final funcionaría.

nom_jug = pd.Series({"name_Complet":[jugadors['name_Complet'][i]**[0]**})

Pero hoy no puedo probarlo!

**Comment by AlvaroDiazS** [comment]
No hay problema. Mañana me pongo con las tareas pendientes. Ya hay una extracción completa de temporada a temporada, son 1100 filas aproximadamente, solo jugadores en activos. Ha tardado 80 minutos

**Comment by dleiva29** [comment]
Con respecto a:

Corregir nom_Complet. Treure []

Era quitando los corchetes. 

nom_jug = pd.Series({"name_Complet":jugadors['name_Complet'][i]})


Lo corrijo en tu código?
